### ISSUE TITLE
Connections duplicated on redeploy

### ISSUE THREAD

**Issue by beneuto** [TheThingsNetwork/nodered-app-node#39]
If you redeploy a node-red flow with TTN message node connections then the connection is duplicated (i.e. original connection is not closed) resulting in duplicate messages being generated.

**Comment by johanstokking** [comment]
@beneuto thanks for reporting, we'll investigate this

Feel free to submit a pull request fixing the issue!

**Comment by Oliv4945** [comment]
Hi,

I also have the bug on a fresh node-red install with only TTN node installed.

**Comment by johanstokking** [comment]
This seems quite easy to fix.

Anyone?

See https://github.com/node-red/node-red/issues/893#issuecomment-221696528

**Comment by Oliv4945** [comment]
Thanks, I will try it and do a PR if it works.

**Comment by Oliv4945** [comment]
Its weird. [NPM last release](https://www.npmjs.com/package/node-red-contrib-ttn) is v2.0.1, it does contain the "[done()](https://github.com/TheThingsNetwork/nodered-app-node/blob/f07cbd647ba18d7d1b2a92ed7e3be4f8173c6834/ttn-app/ttn-app.js#L33)" call and the bug is present.

By the way this call [has been removed](https://github.com/TheThingsNetwork/nodered-app-node/commit/8ff75ac48eb4c82515d0c465949c668319898817#diff-b904d0ec6730e9f6ebc943da741b3f00) by @romeovs in v2.0.2. So, did you solved the issue ?

**Comment by johanstokking** [comment]
Right, it has not been deployed. I will do that.

**Comment by johanstokking** [comment]
@Oliv4945 done
