### ISSUE TITLE
Error " Flows stopped due to missing node types."

### ISSUE THREAD

**Issue by cyberman54** [TheThingsNetwork/nodered-app-node#57]
After installing the app-node v2.05 in the node-red UI i see this error:

> Flows stopped due to missing node types.
> ttn app

The app nodes are not working any longer. In the app the drop down list disappeared.

The app nodes are listed under unknown nodes with this error:

> This node is a type unknown to your installation of Node-RED.
> If you deploy with the node in this state, it's configuration will be preserved, but the flow will not start until the missing type is installed.

Reinstallation of node-red and node.js did not help :-(

**Comment by johanstokking** [comment]
1. Do you see other `ttn` nodes, and if so, which ones?
2. Does Node-RED print any errors in the terminal?

**Comment by cyberman54** [comment]
I could solve this by a complete reinstall, assuming that a gRPC version problem causes this issue. closed.

**Comment by mglaeske** [comment]
Same problem here. And it is not possible to fix it with a reeinstall of ttn, because I have a complete new and clean installation!

Precondition:
The node-red is running inside a docker-container on a raspberry pi 3B+.
Node-Red-Image: nodered/node-red-docker:rpi  (this is 0.20.7-rpi)

Steps to reproduce the problem:
1) Install ttn (2.0.5) in a completly empty and new created node-red container (doesn't matter if you do this with the UI or with CLI)
2) Open the ttn-quickstart sample
3) Configure the App-Properties (App ID, Access key)
4) Click "deploy"

You get an error message: "Flows stopped due to missing node types. check logs for details" (for ttn app)

With node-red (same version of node-red and ttn) on a debian 9 system all works properly (even if its inside a docker-container).
But on the raspberry pi the ttn plugin is not usable.

What I do not understand is this:
![Bildschirmfoto von »2019-08-07 18-38-06«](https://user-images.githubusercontent.com/4757595/62640832-b78d9480-b942-11e9-84e9-2709cf375d6b.png)
With the installation process I could not see any error messages. So what does it mean?

**Comment by johanstokking** [comment]
Yeah the Pi setup is unfortunately problematic. I think we ask too much of the Pi with the library that does a compile of gRPC on install.

Apparently there are some platform specific build flags and/or resource constraints. I’d suggest using the MQTT input node directly in Node-RED if you just use streaming data.

For V3 we probably stick with that anyway as the upside for TTN nodes just for streaming data is very little.
